GET https://github.com/login/oauth/authorize?client_id=4859a02eb577a7db4e4b&redirect_uri=https://localhost:7114/oauth/callback&login=etogm&scope=user&state=asddwd

###

POST https://github.com/login/oauth/access_token?client_id=4859a02eb577a7db4e4b&client_secret=50606605031cad9bee3e110b0d0d59ed347df778&code=39ec8eb654c95004f95c&redirect_uri=https://localhost:7114/oauth/callback


###

GET https://localhost:7114/api/v1/products/test
Authorization: Bearer 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

###

GET https://api.github.com/user
Authorization: Bearer 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


###

POST https://localhost:7065/api/v1/users/ae828df0-0c02-4f14-b4e5-c81ead4db879/products
Content-Type: application/json
{
    "id": "ae828df0-0c02-4f14-b4e5-c81ead4db879",
    "name": "product",
    "description": "desc",
    "amount": 1.0,
    "price": {
        "amount": 10.0,
        "currency": 0
    }
}